.TH  DLA_RPVGRW 1 "November 2008" "    LAPACK routine (version 3.2)                                 " "    LAPACK routine (version 3.2)                                 " 
.SH NAME
DLA_RPVGRW - computes ..
.SH SYNOPSIS
.TP 17
DOUBLE PRECISION
FUNCTION DLA_RPVGRW( N, NCOLS, A, LDA, AF, LDAF )
.TP 17
.ti +4
IMPLICIT
NONE
.TP 17
.ti +4
INTEGER
N, NCOLS, LDA, LDAF
.TP 17
.ti +4
DOUBLE
PRECISION A( LDA, * ), AF( LDAF, * )
.SH PURPOSE
DLA_RPVGRW computes ... .
.SH ARGUMENTS
