.TH  ILAVER 1 "November 2008" " LAPACK routine (version 3.2) " " LAPACK routine (version 3.2) " 
.SH NAME
ILAVER - subroutine return the Lapack version  Arguments ========= VERS_MAJOR (output) INTEGER  return the lapack major version VERS_MINOR (output) INTEGER  return the lapack minor version from the major version VERS_PATCH (output) INTEGER  return the lapack patch version from the minor version =====================================================================   =====================================================================    =====================================================================    
.SH SYNOPSIS
.TP 19
SUBROUTINE ILAVER(
VERS_MAJOR, VERS_MINOR, VERS_PATCH )
.SH PURPOSE
This subroutine return the Lapack version
