.TH  SLA_GBRPVGRW 1 "November 2008" "    LAPACK routine (version 3.2)                                 " "    LAPACK routine (version 3.2)                                 " 
.SH NAME
SLA_GBRPVGRW - computes ..
.SH SYNOPSIS
.TP 14
REAL FUNCTION
SLA_GBRPVGRW( N, KL, KU, NCOLS, AB, LDAB, AFB,
LDAFB )
.TP 14
.ti +4
IMPLICIT
NONE
.TP 14
.ti +4
INTEGER
N, KL, KU, NCOLS, LDAB, LDAFB
.TP 14
.ti +4
REAL
AB( LDAB, * ), AFB( LDAFB, * )
.SH PURPOSE
SLA_GBRPVGRW computes ... .
.SH ARGUMENTS
