.TH  SLA_RPVGRW 1 "November 2008" "    LAPACK routine (version 3.2)                                 " "    LAPACK routine (version 3.2)                                 " 
.SH NAME
SLA_RPVGRW - computes ..
.SH SYNOPSIS
.TP 14
REAL FUNCTION
SLA_RPVGRW( N, NCOLS, A, LDA, AF, LDAF )
.TP 14
.ti +4
IMPLICIT
NONE
.TP 14
.ti +4
INTEGER
N, NCOLS, LDA, LDAF
.TP 14
.ti +4
REAL
A( LDA, * ), AF( LDAF, * )
.SH PURPOSE
SLA_RPVGRW computes ... .
.SH ARGUMENTS
