.TH  ZLA_RPVGRW 1 "November 2008" "    LAPACK routine (version 3.2)                                 " "    LAPACK routine (version 3.2)                                 " 
.SH NAME
ZLA_RPVGRW - computes ..
.SH SYNOPSIS
.TP 17
DOUBLE PRECISION
FUNCTION ZLA_RPVGRW( N, NCOLS, A, LDA, AF, LDAF )
.TP 17
.ti +4
IMPLICIT
NONE
.TP 17
.ti +4
INTEGER
N, NCOLS, LDA, LDAF
.TP 17
.ti +4
COMPLEX*16
A( LDA, * ), AF( LDAF, * )
.SH PURPOSE
ZLA_RPVGRW computes ... .
.SH ARGUMENTS
